### PR TITLE
Add support for relative line number expressions

### PR DESCRIPTION
**Pull request by obycode**
For example:
```
// CHECK: file.c:[[# @LINE + 3]]:8: error
```

### CODE REVIEW

**Comment by stanislaw** [comment]
Thank you for your contribution. 

Could you provide some context: does this feature trace back to the behavior of LLVM FileCheck?

It would be great if you could also document this enhancement and add the LIT/FileCheck integration test.

**Comment by obycode** [comment]
Yes, this corresponds to a feature from LLVM's FileCheck. See [here](https://llvm.org/docs/CommandGuide/FileCheck.html#filecheck-pseudo-numeric-variables).

Sure, I will add some documentation and testing for this feature.

**Comment by obycode** [comment]
Ok, I added a paragraph to 05-check-commands.rst and a simple test under lit-and-filecheck.

**Comment by stanislaw** [comment]
I have refactored and improved your change a little, see https://github.com/mull-project/FileCheck.py/pull/166/commits/7ba5dfa134b654bbdde90a86f41fa5561924c4a3. The `1` was missing, and this prevented multiple `LINE` variables from being matched.

Also, all itests are tested against both LLVM FileCheck and FileCheck.py. It turns out that LLVM 8 does not support this `[[# @LINE + 3]]`. This is not a problem because I have to update the test suite to use newer versions of LLVM anyway.

And finally, if an expression with `@LINE` cannot be matched by LLVM FileCheck, it produces a rather obscure error message that I don't want to replicate in the Python code:

```
/Users/Stanislaw/workspace/projects/code/FileCheck.py/tests/integration/tests/extra_features/pseudo_numeric_variables/01_line_variable_once/filecheck.check:1:8: error: CHECK: expected string not found in input
CHECK: this line is to be matched with number [[# @LINE + 3 ]]
       ^
<stdin>:1:1: note: scanning from here
this line not to be matched
^
<stdin>:1:1: note: uses undefined variable(s): "@LINE"
this line not to be matched
^
<stdin>:2:1: note: possible intended match here
this line is to be matched with number 2
^
```

I find this part confusing: `undefined variable(s): "@LINE"` because the underlying cause is that the LINE is actually defined, but a string with a number cannot be matched.

**Comment by stanislaw** [comment]
The [0.0.21](https://pypi.org/project/filecheck/) is released. Please give it a try.

**Pull request merged**
